#include "lifted_abi.h"

static inline uint64_t lift_flag_width_mask(uint32_t width) { return width == 8u ? UINT64_C(0xFF) : width == 16u ? UINT64_C(0xFFFF) : width == 32u ? UINT64_C(0xFFFFFFFF) : UINT64_MAX; }
static inline uint64_t lift_flag_sign_bit(uint32_t width) { return width == 8u ? UINT64_C(0x80) : width == 16u ? UINT64_C(0x8000) : width == 32u ? UINT64_C(0x80000000) : UINT64_C(0x8000000000000000); }
static inline uint32_t lift_flag_parity(uint64_t value) { uint32_t byte = (uint32_t)value & 0xFFu; byte ^= byte >> 4u; byte &= 0xFu; return (((UINT32_C(0x6996) >> byte) & 1u) == 0u) ? LIFT_FLAG_PF : 0u; }
static inline uint32_t lift_flag_szp(uint64_t value, uint32_t width) { uint64_t truncated = value & lift_flag_width_mask(width); uint32_t flags = lift_flag_parity(truncated); if (truncated == 0u) { flags |= LIFT_FLAG_ZF; } if ((truncated & lift_flag_sign_bit(width)) != 0u) { flags |= LIFT_FLAG_SF; } return flags; }

void LIFT_CDECL lift_flags_logic(LiftCpu* cpu, uint64_t result, uint32_t width) { cpu->eflags = (cpu->eflags & ~(LIFT_FLAG_CF | LIFT_FLAG_PF | LIFT_FLAG_AF | LIFT_FLAG_ZF | LIFT_FLAG_SF | LIFT_FLAG_OF)) | lift_flag_szp(result, width); }
void LIFT_CDECL lift_flags_add(LiftCpu* cpu, uint64_t left, uint64_t right, uint64_t carry, uint64_t result, uint32_t width) { uint64_t mask = lift_flag_width_mask(width); uint64_t sign = lift_flag_sign_bit(width); uint64_t l = left & mask; uint64_t r = right & mask; uint64_t partial = (l + r) & mask; uint64_t truncated = result & mask; uint32_t flags = lift_flag_szp(truncated, width); if (partial < l || (carry != 0u && truncated < partial)) { flags |= LIFT_FLAG_CF; } if (((~(l ^ r) & (l ^ truncated)) & sign) != 0u) { flags |= LIFT_FLAG_OF; } if (((l ^ r ^ truncated) & 0x10u) != 0u) { flags |= LIFT_FLAG_AF; } cpu->eflags = (cpu->eflags & ~(LIFT_FLAG_CF | LIFT_FLAG_PF | LIFT_FLAG_AF | LIFT_FLAG_ZF | LIFT_FLAG_SF | LIFT_FLAG_OF)) | flags; }
void LIFT_CDECL lift_flags_sub(LiftCpu* cpu, uint64_t left, uint64_t right, uint64_t borrow, uint64_t result, uint32_t width) { uint64_t mask = lift_flag_width_mask(width); uint64_t sign = lift_flag_sign_bit(width); uint64_t l = left & mask; uint64_t r = right & mask; uint64_t truncated = result & mask; uint32_t flags = lift_flag_szp(truncated, width); if (l < r || (borrow != 0u && l == r)) { flags |= LIFT_FLAG_CF; } if ((((l ^ r) & (l ^ truncated)) & sign) != 0u) { flags |= LIFT_FLAG_OF; } if (((l ^ r ^ truncated) & 0x10u) != 0u) { flags |= LIFT_FLAG_AF; } cpu->eflags = (cpu->eflags & ~(LIFT_FLAG_CF | LIFT_FLAG_PF | LIFT_FLAG_AF | LIFT_FLAG_ZF | LIFT_FLAG_SF | LIFT_FLAG_OF)) | flags; }
