#pragma once

#include <cstdint>

enum class SferaMbcRuntimeWindowOperation : std::uint32_t
{
    Create = 0,
    Destroy = 1,
    DisplayWidth = 2,
    DisplayHeight = 3,
    TextHeight = 4,
    FontHeight = 5,
    LineOffset = 6,
    TakeInput = 7,
    HitTest = 8,
    Visible = 9,
    Bounds = 10,
    TextSize = 11,
    GlyphWidth = 12,
    Scrollable = 13,
    CursorPosition = 14,
    SystemCursorVisible = 15,
    SystemCursorKind = 16,
    CursorKind = 17,
    CursorImage = 18,
    CursorText = 19,
    Open = 20,
    Close = 21,
    PollEvent = 22,
    SetText = 23,
    ControlAt = 24,
    SendMessage = 25,
    GetText = 26,
    SystemEvent = 27,
    WindowUnderCursor = 28,
    ItemAt = 29,
    SavedPositionsSize = 30,
    ReadSavedPositions = 31,
    WriteSavedPositions = 32,
    Position = 33,
    Size = 34,
    Description = 35,
    Tooltip = 36,
    Options = 37,
    EscapeWindow = 38,
    LegacyCreateDialog = 39,
    LegacyDestroyDialog = 40,
    LegacyPollDialogEvent = 41,
    LegacySendDialogMessage = 42,
    LegacyDialogItem = 43,
    LegacySetDialogText = 44,
    LegacyGetDialogText = 45,
    Shutdown = 46,
    LegacyPumpMessages = 47,
    ActiveWindow = 55,
    LoadingProgress = 78,
    FinishLoading = 79
};
