#include "script/NativeDeclarations.h"
#include <algorithm>
#include <stdexcept>

namespace
{
int compareModule(std::string_view left, std::string_view right)
{
    for (std::size_t i = 0; i < std::min(left.size(), right.size()); ++i)
    {
        const auto byte = static_cast<unsigned char>(left[i]);
        const auto folded = byte >= 'A' && byte <= 'Z' ? byte + ('a' - 'A') : byte;
        if (folded != static_cast<unsigned char>(right[i]))
            return folded < static_cast<unsigned char>(right[i]) ? -1 : 1;
    }
    return left.size() == right.size() ? 0 : left.size() < right.size() ? -1 : 1;
}
constexpr std::string_view symbols[] = {
    "ADDCO",
    "ActivatePopup",
    "AddCheck",
    "AddEnemy",
    "AddInfo",
    "AddPlayerGVG",
    "AddPrayer",
    "AddToDiary",
    "AddToIgnoreList",
    "AddUser",
    "AddUserInit",
    "AddWght",
    "AngleBound",
    "AngleOffset",
    "Anim",
    "AppKey",
    "AskAlly",
    "AskClanSymbol",
    "AskForFile",
    "AskLnk",
    "AskMemb",
    "AtoR",
    "AttachText",
    "AttachType",
    "AutoMode",
    "BalanceGVG",
    "BankOper",
    "BeFree",
    "Bezier",
    "BezierVA",
    "BnkTrd",
    "BoundValue",
    "BuyIt",
    "BuyItBnk",
    "CPar",
    "CUSEM",
    "CalcByLevel",
    "CalcByLevelOnlyDamages",
    "CalcByLevel_ComputeCoeffs",
    "CalcMacroID",
    "CalcRash",
    "CalcRequirs",
    "CalcType",
    "CallEnd",
    "CallLink",
    "CallPict",
    "CamOff",
    "CamOn",
    "CanBeTraded",
    "CenterObj",
    "ChangeAmount",
    "ChatHdl",
    "CheckActionHelp",
    "CheckCanUseOnDistance",
    "CheckForTrade",
    "CheckFree",
    "CheckIndex",
    "CheckLink",
    "CheckLinking",
    "CheckOpenRights",
    "CheckPut",
    "CheckRights",
    "CheckRoom",
    "CheckTest",
    "CheckWeapon",
    "CheckWght",
    "ClearRooms",
    "ClearScale",
    "CloseCont",
    "CloseDiary",
    "CloseScroll",
    "ComputeParamsCrc",
    "ConnResult",
    "ControlOff",
    "ControlOn",
    "ConvertGXPInRealType",
    "CopyAb",
    "CountAnim",
    "CountKnot",
    "CraftString",
    "CreateObj",
    "CreateObjWait",
    "CreateProgressBar",
    "CreateUmap",
    "CrystalsCantPutOnPuppet",
    "Cursor",
    "DDBG",
    "DHunger",
    "DecStonesCntr",
    "DecodeClannameForEmblem",
    "DelMis",
    "DelTime",
    "DeletePlayerGVG",
    "DeltaAngleBound",
    "DestroyObj",
    "DestroyProgressBar",
    "DigSeparate",
    "DigSeparateInt",
    "DirectOfObj",
    "DnD",
    "DnDRes",
    "DnDResP",
    "DoBoom",
    "DrawScale",
    "Effect",
    "EffectWrapper",
    "EnableEmptyChecks",
    "EnableShopButton",
    "Ensc",
    "FCls",
    "FFLBP",
    "FillBalanceGVG",
    "FillPlayersGVG",
    "FillSeed",
    "FillSkinParams",
    "FloatArrayAdd",
    "FlyWeapon",
    "FormatText",
    "FreeIt",
    "FreeIt1",
    "GCHID",
    "GCIID",
    "GCIName",
    "GCIRange",
    "GCN",
    "GEFF",
    "GENM",
    "GETLG",
    "GETPD",
    "GIRP",
    "GMID",
    "GMOD",
    "GPNT",
    "GSCHF",
    "GTST",
    "GetABG",
    "GetActionName",
    "GetAddrs",
    "GetAlch",
    "GetAllyList",
    "GetAmount",
    "GetAntiHackNitkaCount",
    "GetBank",
    "GetBankMoney",
    "GetBonusInfo",
    "GetBoss",
    "GetBossLvl",
    "GetCS",
    "GetCamNorm",
    "GetCanUseWebShopAndClaim",
    "GetCaster",
    "GetCastleName",
    "GetCastleNum",
    "GetCharge",
    "GetChatPrefix",
    "GetClanName",
    "GetClanSymbInit",
    "GetConfVis",
    "GetCrcBufferSize",
    "GetCrystalType",
    "GetCsID",
    "GetCsLevel",
    "GetDirAndSpeed",
    "GetDir_ParamsCrc",
    "GetEar",
    "GetEnt",
    "GetFloatArgument",
    "GetGlobalCont",
    "GetGuardLevel",
    "GetHand",
    "GetHealth",
    "GetHealth_m2",
    "GetHrLicPrice",
    "GetIDArgument",
    "GetInfo",
    "GetIntegerArgument",
    "GetIslLvl",
    "GetItemID",
    "GetKomiss",
    "GetLetter",
    "GetLevel",
    "GetLicTrade",
    "GetLvlClass",
    "GetMBLnam",
    "GetMMChr",
    "GetMName",
    "GetMainServerURL",
    "GetMaxCharge",
    "GetMisXZ",
    "GetModel",
    "GetModifiers",
    "GetModifs",
    "GetModifsArr",
    "GetMoney",
    "GetMulti",
    "GetMusic",
    "GetMySlot",
    "GetNitkaCountFromServer",
    "GetNitkaCountReceived",
    "GetNitkaInfo",
    "GetObjCstlGuard",
    "GetObjHan",
    "GetP",
    "GetPUID",
    "GetParam",
    "GetParent",
    "GetPersMsg",
    "GetPictsPointer",
    "GetPlName",
    "GetPlayerID",
    "GetPlayerLevel",
    "GetPlayerName",
    "GetPrice",
    "GetProperty",
    "GetQuestTargetPoint",
    "GetRandLvl",
    "GetRealPuppSlotIndex",
    "GetRndName",
    "GetRoom",
    "GetRoomCoord",
    "GetRootParent",
    "GetScale",
    "GetShopID",
    "GetSids",
    "GetSlotID",
    "GetSlotsNum",
    "GetSpecial",
    "GetSpecialPoint",
    "GetSpecialPointTelep",
    "GetStCsGuard",
    "GetState",
    "GetStringArgument",
    "GetSysText",
    "GetTP",
    "GetTableTime",
    "GetTagParent",
    "GetTarifForRandBox",
    "GetTmntState",
    "GetTmntTimeLeft",
    "GetTmntType",
    "GetTokenLvl",
    "GetTotDTipsNumber",
    "GetTournamentId",
    "GetUBonus",
    "GetUniqueGeneration",
    "GetUniqueID",
    "GetUseDist",
    "GetUseTout",
    "GetUsedElixirTime",
    "GetWear",
    "GetWeight",
    "GetXYZ",
    "Getabg",
    "GetddHan",
    "GetddWin",
    "Getowner",
    "GetpID",
    "Getxyz",
    "GotTrap",
    "HavePassw",
    "HavePrefZSH",
    "HideBank",
    "HideConsole",
    "HideMinimapWindow",
    "HideTotDWindow",
    "HideWebShopWindow",
    "INCB",
    "ITSOFF",
    "IfInv",
    "IfPuppet",
    "IfTeleported",
    "IfWinMacros",
    "IgnoreSender",
    "IgnoreUseFreq",
    "InHand",
    "InIntDiapasons",
    "InitAI",
    "InitChar",
    "InitCharOwn",
    "InitCharPC",
    "InitClanSymb",
    "InitObj",
    "InputDone",
    "InvOff",
    "InvOn",
    "InvTrig",
    "InvertAI",
    "IsBookInTrade",
    "IsChatFocus",
    "IsChern",
    "IsClanHaveEff",
    "IsClanHaveSymbol",
    "IsClearExtra",
    "IsCommandEmpty",
    "IsControllVirus",
    "IsDigit",
    "IsExit",
    "IsExtra",
    "IsForceDamager",
    "IsItemHaveTiming",
    "IsItemType",
    "IsLetter",
    "IsLetterUnderscore",
    "IsLocalFileExist",
    "IsNpc_Virt",
    "IsOpened",
    "IsOwn",
    "IsReceived",
    "IsUnderSphere",
    "IsUnderground",
    "IsUnique",
    "IsWebShopWindowOn",
    "IsWhitespace",
    "Killed",
    "LID",
    "LLTOI",
    "LastACC",
    "LoadGame",
    "LoadIgnoreList",
    "LoadKeys",
    "LoadLab",
    "LoadModel",
    "LoadMsgGroup",
    "LoadMulti",
    "LoadNewMsgGroup",
    "LoadPreset",
    "LoadSST",
    "LoadSSTW",
    "LoadStuff",
    "LoadTotDParams",
    "LoadTotDText",
    "LoadUnique",
    "LoadiDiapFromFile",
    "LostItem",
    "LostItem2",
    "LotteryResult",
    "MEM",
    "MKM",
    "MPRT",
    "MUseWith",
    "MallocBuf",
    "MaxDist",
    "MdlName",
    "MinDist",
    "ModTpl",
    "Model",
    "ModifsLoaded",
    "MoveObj",
    "NCity",
    "NPL",
    "NSquare",
    "NormalXYZ",
    "NormalXZ",
    "NotEmptyCont",
    "NumOfPlayers",
    "NumToModel",
    "OBZVR",
    "OpenB",
    "OriginCsBonus",
    "PCNThit",
    "Params",
    "ParseCommand",
    "ParseDateTime",
    "ParseItemString",
    "ParseiDiapason",
    "Paused",
    "PercentReceived",
    "Pet",
    "PlFromBuf",
    "PlToBuf",
    "PlaySnd",
    "PlayerName",
    "PopMe",
    "PopupResult",
    "PrintPastTime",
    "ProcessCommand",
    "ProcessConsole",
    "PullOut",
    "PuppetOff",
    "PuppetOn",
    "PuppetTrig",
    "PutHere",
    "PutMoney",
    "QueryInit",
    "QueryShowWebShop",
    "RGTGS",
    "RSTT",
    "RVCT",
    "RcvUser",
    "ReLoadiDiapFromFile",
    "Recalc",
    "ReceiveTmntData",
    "RefreshClanSymb",
    "RegionType",
    "RemoveFromIgnoreList",
    "ResetParams",
    "ResetSkinData",
    "ResetUIOnServerJump",
    "RestoreParams",
    "Run_StartWin",
    "SCHN",
    "SETMON",
    "SKeyAlarm",
    "SMSG",
    "SOffer",
    "SPDEFF",
    "SRVC",
    "SSCL",
    "STW",
    "SVis",
    "SVisChar",
    "SaveGame",
    "SaveReturn",
    "SaveSetup",
    "SaveTotDParams",
    "SayChat",
    "SearchFreeSlotAndPut",
    "SeekFor",
    "SeekMap",
    "SeekTag",
    "SeekTagInsideNoRecursive",
    "SelectChar",
    "Selected",
    "SelfHeal",
    "SendAllyAsk",
    "SendAnim",
    "SendCBookItem",
    "SendConsole",
    "SendConsoleRequest",
    "SendDnDRes",
    "SendHand",
    "SendNPass",
    "SendOffer",
    "SendPassword",
    "SendPress",
    "SendSwordEff",
    "SendSys",
    "SendSys2",
    "SendSys3",
    "SendSys4",
    "SendToRegM",
    "SetABG",
    "SetAllyList",
    "SetAmount",
    "SetClan",
    "SetClanName",
    "SetClanXZ",
    "SetCursType",
    "SetDebug",
    "SetDelCharRes",
    "SetEnable",
    "SetFlagLoadscrOnTop",
    "SetGateStatus",
    "SetGuardLevel",
    "SetHand",
    "SetHealth",
    "SetIsland",
    "SetItemGroup",
    "SetLearned",
    "SetLicClan",
    "SetLoadingScreen",
    "SetLvl",
    "SetMaxLvl",
    "SetMis",
    "SetModel",
    "SetModifiers",
    "SetOSST",
    "SetOverFill",
    "SetPacket",
    "SetParent",
    "SetPlayerID",
    "SetPopup",
    "SetProperty",
    "SetRespRadius",
    "SetReturn",
    "SetRunKey",
    "SetShopID",
    "SetShowText",
    "SetSkin",
    "SetSpecab",
    "SetTax",
    "SetTestItFlag",
    "SetTmntState",
    "SetTmntTimeLeft",
    "SetTmntType",
    "SetTradeState",
    "SetTrig",
    "SetUsedElixirTime",
    "SetUsing",
    "SetWall",
    "SetWear",
    "SetXYZ",
    "SetXYZRAD",
    "Setabg",
    "SetddHan",
    "Sethp",
    "Setxyz",
    "ShadowIm",
    "ShadowIm2",
    "ShadowOff",
    "ShadowOff2",
    "ShadowOn",
    "ShadowOn2",
    "ShadowState",
    "Shadowing",
    "Shadowing2",
    "Sheat",
    "ShowActionHelp",
    "ShowBank",
    "ShowConsole",
    "ShowConsoleFailure",
    "ShowEff",
    "ShowHlth",
    "ShowMinimapWindow",
    "ShowTmntStateGVG",
    "ShowTotDWindow",
    "ShowWebShopWindow",
    "ShowWinClan",
    "SndUser",
    "SpeedObj",
    "StartClanEff",
    "StartWinUnhide",
    "StopEffect",
    "StopSwordEff",
    "Stop_StartWin",
    "StrCnt",
    "StringSorting",
    "TABLE",
    "TD",
    "TSTHK",
    "TSTIT",
    "TTAX",
    "TableOff",
    "TableOn",
    "TableTrig",
    "Teleport",
    "TestDup",
    "TestIt",
    "TestMap",
    "TestMe",
    "TestMerge",
    "TestOwnerPID",
    "TestPut",
    "TestUnique",
    "TimeFromSec",
    "TmntPlayerGroup",
    "ToggleConsole",
    "ToggleMinimapWindow",
    "TradeOff",
    "TradeOn",
    "TradeTrig",
    "TraderDown",
    "TurnSkin",
    "TutoMsg",
    "TypeConsole",
    "TypeMission",
    "TypeScroll",
    "TypeScrollMem",
    "UniqueLine",
    "UnloadMsgGroup",
    "UnpackTmntData",
    "UpdateCfg",
    "UpdateHealth",
    "UpdateProgressBar",
    "UpdateSST",
    "UpdateTmntWin",
    "Upload",
    "Use",
    "UseClient",
    "UseOff",
    "UseOwner",
    "UseReturn",
    "UseServer",
    "UseWith",
    "VirEffect",
    "WaitForAsk",
    "WhatContinent",
    "WhatServer",
    "WinAsyncInput",
    "WinAsyncInputNum",
    "WinMacrosOff",
    "WinMacrosOn",
    "WinMacrosTrig",
    "WinUpd",
    "WorkCheck",
    "__cleanse_buffs",
    "__cleanse_viruses",
    "__create_process",
    "__destroy_process",
    "__enumerate_processes",
    "__get_couragef",
    "__kill_monsters",
    "__set_karma",
    "__set_name",
    "__test_console",
    "addStringToTableList",
    "addToSkrijalTxt",
    "allocmem",
    "assembleChatMsg",
    "block_character_move",
    "callCloseCustomerWorkshop",
    "callOpenCustomerWorkshop",
    "chat",
    "checkContinentsDir",
    "checkDragAndDropStart",
    "checkMouseStayingStill",
    "check_is_item_link_to_me",
    "clearChatBuffers",
    "clear_use_tout_working",
    "closeCustomerWorkshop",
    "closeEvacPlayerWin",
    "cm_addItem",
    "cm_addItemNoParams",
    "cm_clear",
    "cm_click",
    "cm_create",
    "cm_destroy",
    "cm_enable",
    "cm_executeFunction",
    "cm_getExecuteResult",
    "cm_hide",
    "cm_isCreated",
    "cm_isMainFunction",
    "cm_isMenuItem",
    "cm_isVisible",
    "cm_setText",
    "cm_setTitle",
    "cm_show",
    "composeWildcard",
    "computeLinesNumber",
    "computeMatchingFunctionsNumber",
    "computeUseDistance",
    "convertTime2Str",
    "createInfoPicture",
    "createInfoSeparatorLine",
    "deleteMeFroupGroup",
    "deleteSomeoneFromGroup",
    "distToProcess",
    "dnts",
    "dumpShopItems",
    "dungeonCheck",
    "empty",
    "enableFistPwr",
    "errhalt",
    "executeCommandByAbbreviation",
    "executeCommandByAcronym",
    "executeCommandByExactName",
    "fGetName",
    "fillparam",
    "froom",
    "gMsg",
    "getAntiCastleCaptureTimer",
    "getBLkID",
    "getBLkType",
    "getChatState",
    "getContinentLoad",
    "getCrcValues",
    "getCreatureLevel",
    "getDungeonNumber",
    "getFistPowerups",
    "getFormulaInfo",
    "getHostPID",
    "getItemName",
    "getLastGVG",
    "getLeader",
    "getLinkingInfo",
    "getMarkOnMapXZ",
    "getMaxHealthAndPrana",
    "getMissionFactorSet",
    "getMoney",
    "getMultiobjGroup",
    "getMultiobjRecord",
    "getMultiobjectScrpt",
    "getNeutralInfo",
    "getPassportShard",
    "getPictName",
    "getPlayerGroupState",
    "getPlayerIDByName",
    "getPlayerInfo",
    "getRoom",
    "getShard",
    "getSkinNum",
    "getTempArrowMode",
    "getTmntData",
    "getUpgradeMoney",
    "getVirusClass",
    "getVirusID",
    "getWasUpdate",
    "getWeaponUseDistance",
    "get_base_dfrquse",
    "get_crc",
    "get_mNumber",
    "get_pathlist",
    "groupDelete",
    "group_new",
    "halt",
    "hideIfInvisible",
    "ifUsing",
    "inCastleZone",
    "inSameGroup",
    "insrtHText2ChatEdit",
    "insrtItemInfo2Edit",
    "invitePlrToGroup",
    "isEvacPlayerAllowed",
    "isFlamount",
    "isGxpItem",
    "isInvisible",
    "isSlotOccupied",
    "isValidAcronym",
    "joinMeAsCandidate",
    "joinSomeone2Group",
    "lid",
    "listMatchingCommands",
    "loadChatFonts",
    "loadItemIDsAndPrefixes",
    "loadMiniChatFonts",
    "lockid",
    "mapXY2SphereXZ",
    "mcl",
    "mgrAlly",
    "mgrBuyIt",
    "mgrChat",
    "mgrCheat",
    "mgrCheckCrc",
    "mgrEffect",
    "mgrElem",
    "mgrFist",
    "mgrGetBonus",
    "mgrGrab",
    "mgrKey",
    "mgrLost",
    "mgrSBought",
    "mgrSSetOffer",
    "mgrSSysMsg",
    "mgrSetClan",
    "mgrSetCoord",
    "mgrSetGroup",
    "mgrSetTrade",
    "mgrSrClan",
    "mgrSrvJump",
    "mgrTable",
    "mgrTmntAction",
    "mgrTmntData",
    "mgrTmntDone",
    "mgrTmntDrop",
    "mgrTmntInfo",
    "mgrTmntShowState",
    "mgrTmntState",
    "mgrTradeWith",
    "mouseOverChat",
    "moveObjectAlongLandscape",
    "openCustomerWorkshop",
    "openEvacPlayerWin",
    "openSlot",
    "pClanName",
    "pEnemies",
    "pModelName",
    "pUSTATE",
    "processAutoDoors",
    "processDragAndDropEnd",
    "processLButtonClick",
    "processLButtonDown",
    "processLButtonUp",
    "processLookOn",
    "processObjectClick",
    "processObjectDrop",
    "processRButtonDown",
    "processRButtonUp",
    "readnext",
    "readstr",
    "receiveArtisanID",
    "receiveCustomerID",
    "receiveInvite2Group",
    "receiveMarkOnMapXZ",
    "receiveMyWorkshop",
    "receivePriceArtisan",
    "receiveWindowHandler",
    "refreshSkin",
    "refreshWinGroupList",
    "resetArtisanData",
    "resetCustomerData",
    "resetDungeonNumber",
    "resetFlagAcceptCraft",
    "resetPassword",
    "runCrcCalculation",
    "runMgrAnticheat",
    "runRefreshWinGroupList",
    "runSayTryRestart",
    "runWinGroup",
    "sayPetition2Plr",
    "sayPrivate2Plr",
    "seekslot",
    "sendChatMsgByParts",
    "sendMarkOnMapXZ",
    "sendSysTextToChat",
    "sendSysTxt2ChatByNum",
    "sendone",
    "sendpop",
    "sendslot",
    "sendsloti",
    "sendsloti1",
    "setArtisanID",
    "setChatState",
    "setContinentLoad",
    "setCostInWorkshop",
    "setCustomerID",
    "setEvilClan",
    "setFill",
    "setFistPowerups",
    "setFlagAcceptCraft",
    "setFlagCloseWindowWorkshop",
    "setFlagFreeSlotsInWorkshop",
    "setGxpItem",
    "setMarkOnCompassByXZ",
    "setMarkOnMapXZ",
    "setPriceArtisan",
    "setWasUpdate",
    "settim",
    "show",
    "smsShowPrizeWindow",
    "smsShowWindow",
    "specialChecksForMerge",
    "sphereXZ2MapXY",
    "stopWinGroupExist",
    "stopWinGroupNew",
    "sysMsgAndText",
    "testfile",
    "thalt",
    "trig",
    "tryToRevertClanKills",
    "turnSkinAndSetVis",
    "use",
    "useItemOnOneself",
    "useItemOnSuperstatic",
    "useItemOnTarget",
    "use_check_frquse",
    "use_check_linking",
    "use_is_stack_use",
    "use_on",
    "use_send_cuse_to_server",
    "valid_filesys_chrs"
};
struct ModuleTag { std::uint16_t tag; std::string_view name; };
constexpr ModuleTag tags[] = {
    {1u, "_main"},
    {2u, "_player"},
    {3u, "_ambc"},
    {4u, "_stat"},
    {5u, "_chat"},
    {6u, "_afix"},
    {10u, "purse"},
    {20u, "room1"},
    {30u, "virus"},
    {31u, "crystal"},
    {40u, "seed"},
    {42u, "crystal_attr_a"},
    {43u, "crystal_attr_b"},
    {44u, "crystal_attr_c"},
    {45u, "crystal_attr_d"},
    {46u, "x2_titul"},
    {47u, "x2_degree"},
    {48u, "x2_tit_degr"},
    {50u, "fb1"},
    {51u, "fb2"},
    {60u, "door1"},
    {61u, "door2"},
    {62u, "telep"},
    {63u, "telep1"},
    {64u, "telep2"},
    {65u, "entry"},
    {66u, "token"},
    {67u, "telep3"},
    {68u, "licence"},
    {69u, "telep4"},
    {70u, "incubator"},
    {71u, "telep5"},
    {72u, "tutomsg"},
    {80u, "cs_table"},
    {81u, "cs_gate"},
    {82u, "cs_chest"},
    {83u, "cs_knot"},
    {90u, "scroll"},
    {91u, "mg_rcp"},
    {95u, "quest"},
    {96u, "labyr"},
    {97u, "packet"},
    {98u, "doorc"},
    {100u, "fernbush"},
    {101u, "door_lk"},
    {102u, "telep6"},
    {103u, "telep7"},
    {104u, "token_pr"},
    {105u, "token_pr_cpy"},
    {106u, "island_pr"},
    {107u, "telep8"},
    {108u, "crystalc"},
    {109u, "crystalcattr"},
    {110u, "clanlicence"},
    {111u, "rilicense"},
    {112u, "rslicense"},
    {113u, "rglicense"},
    {114u, "rtlicense"},
    {115u, "rdlicense"},
    {116u, "goldpurse"},
    {117u, "license_hr"},
    {118u, "license_hrgt"},
    {119u, "license_ph"},
    {120u, "license_phgt"},
    {121u, "pw_buff0"},
    {122u, "pw_buff1"},
    {123u, "pw_buff2"},
    {124u, "pw_buff3"},
    {126u, "town_table"},
    {127u, "tokenst"},
    {128u, "island_token"},
    {129u, "pw_ability"},
    {130u, "scroll_october"},
    {131u, "quest2"},
    {132u, "telep9"},
    {133u, "rgllicense"},
    {134u, "g_lvlup_license"},
    {200u, "npc14"},
    {201u, "npc29"},
    {202u, "npc40"},
    {203u, "npc47"},
    {204u, "npc01"},
    {205u, "npc06"},
    {206u, "npc_virt"},
    {207u, "npc55"},
    {208u, "npc58"},
    {209u, "npc59"},
    {210u, "monster"},
    {211u, "monsterf"},
    {212u, "npc_guide"},
    {213u, "npc_trader"},
    {215u, "monsterc"},
    {216u, "npc_guilder"},
    {217u, "monsterq"},
    {218u, "monsters"},
    {219u, "monstern"},
    {220u, "monsterh"},
    {221u, "npc_questman"},
    {222u, "monsterd"},
    {223u, "monsterdf"},
    {224u, "cs_guard"},
    {225u, "npc_banker"},
    {226u, "_bank"},
    {227u, "fwks"},
    {228u, "fwks2"},
    {229u, "npc_gold"},
    {235u, "st_expball"},
    {236u, "item_bead"},
    {237u, "npc_newyear"},
    {238u, "npc_empty"},
    {239u, "npc_tournament"},
    {240u, "npc_collector"},
    {241u, "item_letter"},
    {300u, "crt02"},
    {301u, "crt51"},
    {302u, "crt03"},
    {400u, "ct_bag"},
    {401u, "ct_ubag"},
    {402u, "ct_chest1"},
    {403u, "ct_jar"},
    {404u, "ct_sac_p"},
    {405u, "ct_sac_s"},
    {406u, "ct_chest2"},
    {407u, "ct_mbag"},
    {408u, "ct_chest3"},
    {409u, "ct_mbook"},
    {410u, "ct_rbook"},
    {411u, "ct_mbook1"},
    {412u, "ct_mbook2"},
    {413u, "ct_mapbook"},
    {414u, "ct_chest4"},
    {415u, "ct_lab"},
    {416u, "ct_cbag"},
    {417u, "ct_chest5"},
    {418u, "ct_barn"},
    {419u, "ct_sac_m"},
    {420u, "ct_chest6"},
    {421u, "ct_chest7"},
    {422u, "ct_bagd"},
    {423u, "ct_mbook3"},
    {424u, "ct_chest_pr"},
    {425u, "ct_ibag"},
    {426u, "ct_gbag"},
    {427u, "ct_mbook4"},
    {428u, "vn_stonea"},
    {429u, "mg_gmagicpot"},
    {430u, "ct_sbag"},
    {431u, "vn_purge"},
    {432u, "pw_courage"},
    {433u, "pw_couragef"},
    {434u, "vn_exp"},
    {435u, "ar_amulet_refr"},
    {436u, "vn_ret"},
    {437u, "vn_ret_2010"},
    {438u, "vn_ret1"},
    {439u, "pw_fistpwr"},
    {440u, "vn_karma"},
    {441u, "vn_tokensin"},
    {442u, "ct_cbook1"},
    {443u, "pw_couragef1"},
    {444u, "ct_cbook2"},
    {445u, "vn_karma1"},
    {446u, "vn_snowman"},
    {447u, "mortar"},
    {448u, "vn_summon"},
    {449u, "vn_candy"},
    {451u, "pw_finish"},
    {452u, "pw_fb01"},
    {453u, "pw_fb02"},
    {454u, "pw_amilus"},
    {455u, "pw_fb03"},
    {456u, "pw_fb04"},
    {457u, "pw_fb05"},
    {458u, "vn_mirror"},
    {470u, "pw_heal1"},
    {471u, "pw_elixir"},
    {472u, "pw_elixir1"},
    {473u, "pw_fixhunger"},
    {474u, "vn_randbox"},
    {475u, "tournament"},
    {476u, "monster_trap"},
    {477u, "monster_event"},
    {478u, "vn_tnmnt_randbox"},
    {500u, "wp_sword1"},
    {501u, "wp_axe1"},
    {502u, "wp_arbalest1"},
    {503u, "wp_arrow1"},
    {504u, "wp_aroma"},
    {505u, "wp_sword1u"},
    {506u, "wp_sword1st"},
    {507u, "wp_axe_boar"},
    {550u, "jw_diamond"},
    {551u, "jw_diamring"},
    {552u, "jw_rubyring"},
    {553u, "jw_ruby"},
    {554u, "jw_gold"},
    {555u, "jw_ring"},
    {600u, "al_mineral"},
    {601u, "al_flower"},
    {602u, "al_metal"},
    {650u, "fd_apple"},
    {651u, "fd_pear"},
    {652u, "fd_jerky"},
    {653u, "fd_scon"},
    {654u, "fd_fish"},
    {655u, "fd_stockfish"},
    {700u, "st_brushwood"},
    {701u, "st_key"},
    {702u, "st_light1"},
    {703u, "st_map"},
    {704u, "st_chern"},
    {705u, "st_light2"},
    {706u, "st_ear"},
    {707u, "st_coin"},
    {708u, "st_string"},
    {709u, "st_loot"},
    {710u, "st_key2"},
    {711u, "st_light3"},
    {712u, "st_light4"},
    {713u, "fir"},
    {714u, "st_shamp"},
    {715u, "rhomb"},
    {716u, "lottery"},
    {718u, "rock"},
    {750u, "ar_armor"},
    {751u, "ar_amulet"},
    {752u, "ar_shoes"},
    {753u, "ar_shoes2"},
    {754u, "ar_gloves"},
    {755u, "ar_belt"},
    {756u, "ar_shield"},
    {757u, "ar_helm"},
    {758u, "ar_pants"},
    {759u, "ar_bracelet"},
    {760u, "ar_ring"},
    {761u, "ar_armor2"},
    {762u, "ar_ring_s"},
    {770u, "ar_armoru"},
    {771u, "ar_amuletu"},
    {772u, "ar_shoesu"},
    {773u, "ar_shoes2u"},
    {774u, "ar_glovesu"},
    {775u, "ar_beltu"},
    {776u, "ar_shieldu"},
    {777u, "ar_helmu"},
    {778u, "ar_pantsu"},
    {779u, "ar_braceletu"},
    {780u, "ar_ringu"},
    {781u, "ar_armor2u"},
    {800u, "mg_magicpot"},
    {801u, "mg_corn"},
    {802u, "mg_eye"},
    {803u, "mg_magicstove"},
    {804u, "formula"},
    {805u, "mg_workshop"},
    {806u, "flag"},
    {900u, "vn_well"},
    {901u, "vn_stonew"},
    {902u, "vn_stoneb"},
    {903u, "vn_cryst"},
    {904u, "vn_crystq"},
    {950u, "ar_armorf"},
    {951u, "ar_amuletf"},
    {952u, "ar_shoesf"},
    {953u, "ar_glovesf"},
    {954u, "ar_beltf"},
    {955u, "ar_shieldf"},
    {956u, "ar_helmf"},
    {957u, "ar_pantsf"},
    {958u, "ar_braceletf"},
    {959u, "ar_ringf"},
    {960u, "ar_armor2f"},
    {961u, "wp_sword1f"},
    {962u, "wp_axe1f"},
    {963u, "wp_arbalest1f"},
    {990u, "ar_helm_pr"},
    {1000u, "mg_mantraw"},
    {1001u, "mg_mantrab"},
    {2000u, "guild"},
    {2001u, "specab"},
    {2002u, "specab_ga"},
    {2003u, "specab_ha"},
    {2004u, "specab_ba"},
    {2005u, "specab_ca"},
    {2006u, "specab_ea"},
    {2007u, "specab_gb"},
    {2008u, "specab_fa"},
    {2009u, "specab_ic"},
    {2010u, "specab_ma"},
    {2011u, "specab_mb"},
    {2012u, "specab_mc"},
    {2013u, "specab_na"},
    {2014u, "specab_nb"},
    {2015u, "specab_nc"},
    {3000u, "_pcontrol"},
    {3001u, "vir1000"},
    {3002u, "vir1001"},
    {3003u, "vir1002"},
    {3004u, "vir1003"},
    {3005u, "vir1004"},
    {3006u, "vir1005"},
    {3007u, "vir1006"},
    {3008u, "vir1007"},
    {3009u, "vir1008"},
    {3010u, "vir1009"},
    {3011u, "vir1010"},
    {3012u, "vir1011"},
    {3013u, "vir1012"},
    {3014u, "vir1013"},
    {3015u, "vir1014"},
    {3016u, "vir1015"},
    {3017u, "vir1016"},
    {3018u, "vir1017"},
    {3019u, "vir1018"},
    {3020u, "vir1019"},
    {3021u, "vir1020"},
    {3022u, "vir1021"},
    {3023u, "vir1022"},
    {3024u, "vir1023"},
    {3025u, "vir1024"},
    {3026u, "vir1025"},
    {3027u, "vir1026"},
    {3028u, "vir1027"},
    {3029u, "vir1028"},
    {3030u, "vir1030"},
    {3031u, "vir1031"},
    {3032u, "vir1032"},
    {3033u, "vir1034"},
    {3034u, "vir1035"},
    {3035u, "vir1036"},
    {3036u, "vir1037"},
    {3037u, "vir1038"},
    {3038u, "vir1039"},
    {3047u, "vir1111"},
    {3048u, "vir2020"},
    {3049u, "vir2021"},
    {3050u, "_ai"},
    {3051u, "_char"},
    {3052u, "_cobj"},
    {3056u, "vir1040"},
    {3057u, "vir1041"},
    {3058u, "vir1042"},
    {3059u, "vir1043"},
    {3060u, "vir1044"},
    {3061u, "vir1045"},
    {3062u, "vir1046"},
    {3063u, "vir1047"},
    {3064u, "_files"},
    {3065u, "_gmsg"},
    {3066u, "_inv"},
    {3067u, "_invalch"},
    {3068u, "_inventory"},
    {3069u, "_mission"},
    {3070u, "_puppet"},
    {3071u, "_table"},
    {3072u, "_trade"},
    {3073u, "_tradegold"},
    {3074u, "shop"},
    {3075u, "claim_blank"},
    {3076u, "vir1048"},
    {3077u, "vir1049"},
    {3078u, "_player_webshop"},
    {3079u, "vir1050"},
    {3080u, "token_s"},
    {3081u, "npc_father_frost"},
    {3082u, "vir1051"},
    {3083u, "tmnt_hostage"},
    {3084u, "ct_bag_herb"}
};
}

std::span<const SferaNativeModule> SferaNativeCatalog::modules() { return nativeModules; }

const SferaNativeModule *SferaNativeCatalog::find(std::string_view name)
{
    const auto found = std::lower_bound(std::begin(nativeModules), std::end(nativeModules), name,
        [](const auto &module, auto key) { return compareModule(key, module.name) > 0; });
    return found != std::end(nativeModules) && compareModule(name, found->name) == 0 ? found : nullptr;
}

std::uint32_t SferaNativeCatalog::findSymbol(std::string_view name)
{
    const auto found = std::lower_bound(std::begin(symbols), std::end(symbols), name);
    return found != std::end(symbols) && *found == name ? static_cast<std::uint32_t>(found - std::begin(symbols) + 1) : 0u;
}

std::string_view SferaNativeCatalog::symbolName(std::uint32_t symbol)
{
    return symbol > 0 && symbol <= std::size(symbols) ? symbols[symbol - 1] : std::string_view{};
}

std::string_view SferaNativeCatalog::moduleName(std::uint32_t tag)
{
    const auto found = std::lower_bound(std::begin(tags), std::end(tags), tag,
        [](const auto &entry, auto value) { return entry.tag < value; });
    return found != std::end(tags) && found->tag == tag ? found->name : std::string_view{};
}

std::uint32_t SferaNativeCatalog::findModuleTag(std::string_view name)
{
    for (const auto &entry : tags)
        if (compareModule(name, entry.name) == 0)
            return entry.tag;
    return UINT32_MAX;
}

const SferaNativeObjectInitializer &SferaNativeCatalog::objectType(std::uint16_t type)
{
    if (type >= std::size(nativeObjectTypes))
        throw std::out_of_range("Invalid native object type");
    return nativeObjectTypes[type];
}
